site_name: PromptMask
theme:
  name: readthedocs
repo_url: https://github.com/cxumol/promptmask
repo_name: cxumol/promptmask
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            show_root_heading: no
            show_source: no
            show_submodules: true
nav:
  - Home: index.md
  - API Reference: reference.md